version: '3.8'

services:
  backend:
    build: ./backend
    image: jishnu7676/quantummed-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns

  frontend:
    build: ./frontend
    image: jishnu7676/quantummed-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5001:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri file:///mlflow --artifacts-destination /mlflow --default-artifact-root /mlflow
    volumes:
      - ./mlruns:/mlflow
